site_name: Infraestructuras de datos espaciales y estándares de geoservicios
site_url: https://gss-mtig.github.io/sdis-mgeo/
site_description: Infraestructuras de datos espaciales y estándares de geoservicios.
site_author: sdis-mgeo
theme:
  name: 'material'
  language: 'es'
  highlightjs: true

markdown_extensions:
  - codehilite:
      linenums: True
  - admonition
  - pymdownx.magiclink
  - pymdownx.superfences
  - footnotes
repo_url: "https://github.com/gss-mtig/sdis-mgeo"

nav:
- Home: index.md
- Infraestructuras de datos espaciales (IDEs):
  - 1. Introducción a las IDE's: introduccion_a_las_ides.md
  - 2. Catálogo de Metadatos: catalogo_metadatos.md
  - 3. Iniciativas:
    - 3.1. IDEE: idee.md
    - 3.2. IDEC: idec.md
    - 3.3. INSPIRE: inspire.md
    - 3.4. Otras IDEs: otras_ides.md
  - 4. Marco legal:
    - 4.1. LISIGE: lisige.md
- Metadatos: 
  - 1. Qué es un metadato: metadatos.md
  - 2. Estándares ISO: estandares_ISO.md
- Estándares OCG: 
  - 1. Qué es OGC?: estandares_OCG.md
  - 2. WMS: wms.md
  - 3. WMTS: wmts.md
  - 4. OGC APIs:
    - 4.1. APIs: api.md
    - 4.2. Features: ogc_api_features.md
  - 5. WFS: wfs.md
  - 6. GML: gml.md
  - 7. SLD: sld.md
  - 8. SOS: sos.md
  - 9. CSW: csw.md
  - 10. Otros: otros.md       
- Instalación de programas: instalacion_de_programas.md
- Clientes de mapas: clientes_de_mapa.md
- Creación de Metadatos: creacion_metadatos.md
- Servidores de mapas: servidores_de_mapa.md
- Publicar datos en una base de datos online: bd_online.md

plugins:
    - search
